#!/usr/bin/env bash
set -euo pipefail

play() {
    afplay "${dir}/sounds/${1}.wav" &
}

dir="$(dirname "${BASH_SOURCE[0]}")"

play start

status=0
"$@" || status="$?"

if [[ "$status" == "0" ]]; then
    play success
elif [[ "$status" == "2" ]]; then
    play lint_error
else
    play fail
fi
